#include <stdio.h>
#include <string.h>
#include "ft_printf.h"

int	main(void)
{	
	
	printf("----------------------------------------------string--------------------------------------------------\n");
	printf("ORIGINAL\n");
	printf("\n");
	printf("%-60s: |%s|","format identifier", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%20s|", "with minimum field (20) width", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%-20s|", "minimum field (20) left align", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%-20s|", "minimum field (20) left align", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%.8s|", "precision (8) field", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%-.8s|", "precision (8) field left align", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%20.8s|", "minimum (20) and precision (8) field", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%-20.8s|", "minimum (20) and precision (8) field left align", "quarenta e dois");
	printf("\n");
	printf("%-60s: |%*.*s|", "minimum (20) and precision (8) field left align", -20, -8, "quarenta e dois");
	printf("\n\n");
	ft_printf("MY FT_PRINTF\n");
	ft_printf("\n");
	ft_printf("%-60s: |%s|","format identifier", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%20s|", "with minimum field (20) width", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%-20s|", "minimum field (20) left align", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%-20s|", "minimum field (20) left align", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%.8s|", "precision (8) field", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%-.8s|", "precision (8) field left align", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%20.8s|", "minimum (20) and precision (8) field", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%-20.8s|", "minimum (20) and precision (8) field left align", "quarenta e dois");
	ft_printf("\n");
	ft_printf("%-60s: |%*.*s|", "minimum (20) and precision (8) field left align", -20, -8, "quarenta e dois");
	ft_printf("\n\n");
	

	printf("---------------------------------------------character----------------------------------------------\n");
	printf("ORIGINAL\n");
	printf("\n");
	printf("%-60s: |%c|","format identifier", 'x');
	printf("\n");
	printf("%-60s: |%2c|", "with minimum field (2) width", 'x');
	printf("\n");
	printf("%-60s: |%-20c|", "minimum field (20) left align", 'x');
	printf("\n");
	printf("%-60s: |%*c|", "minimum (8) field (*) left align", -10, 'x');
	printf("\n");
	printf("\n");
	ft_printf("MY FT_PRINTF\n");
	ft_printf("\n");
	ft_printf("%-60s: |%c|","format identifier", 'x');
	ft_printf("\n");
	ft_printf("%-60s: |%2c|", "with minimum field (2) width", 'x');
	ft_printf("\n");
	ft_printf("%-60s: |%-20c|", "minimum field (20) left align", 'x');
	ft_printf("\n");
	ft_printf("%-60s: |%*c|", "minimum (8) field (*) left align", -10, 'x');
	ft_printf("\n");
	ft_printf("\n");

	printf("-----------------------------------------------integer--------------------------------------------------------\n");
	printf("\n");
	printf("ORIGINAL\n");
	int hex_neg = -0x2a;

	printf("%-60s: |%i|","format identifier", -42);
	printf("\n");
	printf("%-60s: |%20i|", "with minimum field (20) width", -42);
	printf("\n");
	printf("%-60s: |%020i|", "minimum field (20) width with 0's", -42);
	printf("\n");
	printf("%-60s: |%-20i|", "minimum field (20) left align", -42);
	printf("\n");
	printf("%-60s: |%20.1i|", "precision (1) and minimum (20) field", -42);
	printf("\n");
	printf("%-60s: |%.1i|", "precision (1) field", -42);
	printf("\n");
	printf("%-60s: |%-.1i|", "(hex_neg) precision (1) field left align", hex_neg);
	printf("\n");
	printf("%-60s: |%020.10i|", "minimum (20) and precision (10) field", -12345678);
	printf("\n");
	printf("%-60s: |%-20.10i|", "minimum (20) and precision (10) field left align", -12345678);
	printf("\n");
	printf("\n");
	printf("%-60s: |%-*.*i|", "(hex_neg) minimum (20) and precision (1) field left align", 20, 1, hex_neg);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	ft_printf("MY FT_PRINTF\n");
	ft_printf("\n");
	ft_printf("%-60s: |%i|","format identifier", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%20i|", "with minimum field (20) width", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%020i|", "minimum field (20) width with 0's", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%-20i|", "minimum field (20) left align", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%20.1i|", "precision (1) and minimum (20) field", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%.1i|", "precision (1) field", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%-.1i|", "(hex_neg) precision (1) field left align", hex_neg);
	ft_printf("\n");
	ft_printf("%-60s: |%020.10i|", "minimum (20) and precision (10) field", -12345678);
	ft_printf("\n");
	ft_printf("%-60s: |%-20.10i|", "minimum (20) and precision (10) field left align", -12345678);
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("%-60s: |%-*.*i|", "(hex_neg) minimum (20) and precision (1) field left align", 20, 1, hex_neg);
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");

	printf("-------------------------------------------unsigned_integer------------------------------------------------------\n");
	printf("\n");
	printf("ORIGINAL\n");
	printf("%-60s: |%u|","negative input", -42);
	printf("\n");
	printf("%-60s: |%u|","format identifier", 42);
	printf("\n");
	printf("%-60s: |%20u|", "with minimum field (20) width", 42);
	printf("\n");
	printf("%-60s: |%020u|", "minimum field (20) width with 0's", 42);
	printf("\n");
	printf("%-60s: |%-20u|", "minimum field (20) left align", 42);
	printf("\n");
	printf("%-60s: |%20.1u|", "precision (1) and minimum (20) field", 42);
	printf("\n");
	printf("%-60s: |%.1u|", "precision (1) field", 42);
	printf("\n");
	printf("%-60s: |%-.1u|", "(hex_neg) precision (1) field left align", 42);
	printf("\n");
	printf("%-60s: |%-20.1u|", "minimum (20) and precision (1) field left align", 42);
	printf("\n");
	printf("%-60s: |%-*.*u|", "(hex_neg) minimum (20) and precision (1) field left align", 20, 1, 42);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	ft_printf("MY FT_PRINTF\n");
	ft_printf("\n");
	ft_printf("%-60s: |%u|","negative input", -42);
	ft_printf("\n");
	ft_printf("%-60s: |%u|","format identifier", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%20u|", "with minimum field (20) width", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%020u|", "minimum field (20) width with 0's", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%-20u|", "minimum field (20) left align", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%20.1u|", "precision (1) and minimum (20) field", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%.1u|", "precision (1) field", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%-.1u|", "(hex_neg) precision (1) field left align", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%-20.1u|", "minimum (20) and precision (1) field left align", 42);
	ft_printf("\n");
	ft_printf("%-60s: |%-*.*u|", "(hex_neg) minimum (20) and precision (1) field left align", 20, 1, 42);
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");

	printf("---------------------------------------------hex_integer_lowercase----------------------------------------------------\n");
	printf("\n");
	printf("ORIGINAL\n");
	int hex = 0x9f4;
	int integer = 42;
	
	printf("\n");
	printf("%-60s: |%x|","(int) format identifier", integer);
	printf("\n");
	printf("%-60s: |%x|","(hex) format identifier", hex);
	printf("\n");
	printf("%-60s: |%20x|", "(int) with minimum field (20) width", integer);
	printf("\n");
	printf("%-60s: |%20x|", "(hex) with minimum field (20) width", hex);
	printf("\n");
	printf("%-60s: |%020x|", "(int) minimum field (20) width with 0's", integer);
	printf("\n");
	printf("%-60s: |%020x|", "(hex) minimum field (20) width with 0's", hex);
	printf("\n");
	printf("%-60s: |%-20x|", "(int) minimum field (20) left align", integer);
	printf("\n");
	printf("%-60s: |%-20x|", "(hex) minimum field (20) left align", hex);
	printf("\n");
	printf("%-60s: |%20.6x|", "precision (6) and minimum (20) field", hex);
	printf("\n");
	printf("%-60s: |%.6x|", "precision (6) field", integer);
	printf("\n");
	printf("%-60s: |%-.6x|", "(hex_neg) precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-20.6x|", "minimum (20) and precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-*.*x|", "(hex_neg) minimum (20) and precision (6) field left align", 20, 6, hex);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	ft_printf("MY FT_PRINTF\n");
	ft_printf("\n");
	ft_printf("%-60s: |%x|","(int) format identifier", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%x|","(hex) format identifier", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%20x|", "(int) with minimum field (20) width", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%20x|", "(hex) with minimum field (20) width", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%020x|", "(int) minimum field (20) width with 0's", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%020x|", "(hex) minimum field (20) width with 0's", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%-20x|", "(int) minimum field (20) left align", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%-20x|", "(hex) minimum field (20) left align", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%20.6x|", "precision (6) and minimum (20) field", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%.6x|", "precision (6) field", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%-.6x|", "(hex_neg) precision (6) field left align", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%-20.6x|", "minimum (20) and precision (6) field left align", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%-*.*x|", "(hex_neg) minimum (20) and precision (6) field left align", 20, 6, hex);
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");
	printf("---------------------------------------------hex_integer_uppercase----------------------------------------------------\n");
	printf("\n");
	printf("ORIGINAL\n");
	printf("\n");
	printf("%-60s: |%X|","(int) format identifier", integer);
	printf("\n");
	printf("%-60s: |%X|","(hex) format identifier", hex);
	printf("\n");
	printf("%-60s: |%20X|", "(int) with minimum field (20) width", integer);
	printf("\n");
	printf("%-60s: |%20X|", "(hex) with minimum field (20) width", hex);
	printf("\n");
	printf("%-60s: |%020X|", "(int) minimum field (20) width with 0's", integer);
	printf("\n");
	printf("%-60s: |%020X|", "(hex) minimum field (20) width with 0's", hex);
	printf("\n");
	printf("%-60s: |%-20X|", "(int) minimum field (20) left align", integer);
	printf("\n");
	printf("%-60s: |%-20X|", "(hex) minimum field (20) left align", hex);
	printf("\n");
	printf("%-60s: |%20.6X|", "precision (6) and minimum (20) field", hex);
	printf("\n");
	printf("%-60s: |%.6X|", "precision (6) field", integer);
	printf("\n");
	printf("%-60s: |%-.6X|", "(hex_neg) precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-20.6X|", "minimum (20) and precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-*.*X|", "(hex_neg) minimum (20) and precision (6) field left align", 20, 6, hex);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	ft_printf("MY FT_PRINTF\n");
	ft_printf("\n");
	ft_printf("%-60s: |%X|","(int) format identifier", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%X|","(hex) format identifier", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%20X|", "(int) with minimum field (20) width", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%20X|", "(hex) with minimum field (20) width", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%020X|", "(int) minimum field (20) width with 0's", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%020X|", "(hex) minimum field (20) width with 0's", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%-20X|", "(int) minimum field (20) left align", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%-20X|", "(hex) minimum field (20) left align", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%20.6X|", "precision (6) and minimum (20) field", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%.6X|", "precision (6) field", integer);
	ft_printf("\n");
	ft_printf("%-60s: |%-.6X|", "(hex_neg) precision (6) field left align", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%-20.6X|", "minimum (20) and precision (6) field left align", hex);
	ft_printf("\n");
	ft_printf("%-60s: |%-*.*X|", "(hex_neg) minimum (20) and precision (6) field left align", 20, 6, hex);
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");
	ft_printf("\n");

	return (0);
}